#!/bin/sh
while inotifywait -qq -e close_write .; do
    sleep 0.3

    echo  "python makesvg.py > wtcsvg.html"
    python makesvg.py > wtcsvg.html
    cat wtcsvg.html | tail -n +18 | head -n -4  > wtcsvg.svg
done
